import {
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifKz,
    cifPl,
    cifRu,
    cifUs,
    cilAddressBook,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowBottom,
    cilArrowCircleBottom,
    cilArrowCircleTop,
    cilArrowRight,
    cilArrowTop,
    cilBasket,
    cilBell,
    cilBold,
    cilBookmark,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloudDownload,
    cilCloudUpload,
    cilCode,
    cilCog,
    cilCommentSquare,
    cilCreditCard,
    cilCursor,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilEqualizer,
    cilFile,
    cilFilter,
    cilFolderOpen,
    cilGrid,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilInfo,
    cilInput,
    cilItalic,
    cilJustifyCenter,
    cilJustifyLeft,
    cilLayers,
    cilLibrary,
    cilList,
    cilListNumbered,
    cilListRich,
    cilLocationPin,
    cilLockLocked,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMenu,
    cilMinus,
    cilMoon,
    cilNotes,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPrint,
    cilPuzzle,
    cilReportSlash,
    cilSave,
    cilSearch,
    cilSettings,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilStorage,
    cilSun,
    cilSync,
    cilTags,
    cilTask,
    cilTrash,
    cilUnderline,
    cilUser,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilX,
    cilDataTransferDown,
    cilBarChart,
    cilChartLine,
    cilChild,
    cilHistory,
    cilRoom,
    cilBook,
    cilMoney
} from '@coreui/icons';

export const iconSubset = {
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifKz,
    cifPl,
    cifRu,
    cifUs,
    cilAddressBook,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowCircleBottom,
    cilArrowCircleTop,
    cilArrowBottom,
    cilArrowRight,
    cilArrowTop,
    cilBasket,
    cilBell,
    cilBold,
    cilBookmark,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloudDownload,
    cilCloudUpload,
    cilCode,
    cilCog,
    cilCommentSquare,
    cilCreditCard,
    cilCursor,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilEqualizer,
    cilFile,
    cilFilter,
    cilFolderOpen,
    cilGrid,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilInfo,
    cilInput,
    cilItalic,
    cilJustifyCenter,
    cilJustifyLeft,
    cilLayers,
    cilLibrary,
    cilList,
    cilListNumbered,
    cilListRich,
    cilLocationPin,
    cilLockLocked,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMenu,
    cilMinus,
    cilMoon,
    cilNotes,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPrint,
    cilPuzzle,
    cilReportSlash,
    cilSave,
    cilSearch,
    cilSettings,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilStorage,
    cilSun,
    cilSync,
    cilTags,
    cilTask,
    cilTrash,
    cilUnderline,
    cilUser,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilX,
    cilDataTransferDown,
    cilBarChart,
    cilChartLine,
    cilChild,
    cilHistory,
    cilRoom,
    cilBook,
    cilMoney
};

export enum IconSubset {
    cibCcAmex = 'cibCcAmex',
    cibCcApplePay = 'cibCcApplePay',
    cibCcMastercard = 'cibCcMastercard',
    cibCcPaypal = 'cibCcPaypal',
    cibCcStripe = 'cibCcStripe',
    cibCcVisa = 'cibCcVisa',
    cibFacebook = 'cibFacebook',
    cibGoogle = 'cibGoogle',
    cibLinkedin = 'cibLinkedin',
    cibSkype = 'cibSkype',
    cibTwitter = 'cibTwitter',
    cifBr = 'cifBr',
    cifEs = 'cifEs',
    cifFr = 'cifFr',
    cifIn = 'cifIn',
    cifKz = 'cifKz',
    cifPl = 'cifPl',
    cifRu = 'cifRu',
    cifUs = 'cifUs',
    cilAddressBook = 'cilAddressBook',
    cilAlignCenter = 'cilAlignCenter',
    cilAlignLeft = 'cilAlignLeft',
    cilAlignRight = 'cilAlignRight',
    cilApplicationsSettings = 'cilApplicationsSettings',
    cilArrowCircleBottom = 'cilArrowCircleBottom',
    cilArrowCircleTop = 'cilArrowCircleTop',
    cilArrowBottom = 'cilArrowBottom',
    cilArrowRight = 'cilArrowRight',
    cilArrowTop = 'cilArrowTop',
    cilBasket = 'cilBasket',
    cilBell = 'cilBell',
    cilBold = 'cilBold',
    cilBookmark = 'cilBookmark',
    cilCalculator = 'cilCalculator',
    cilCalendar = 'cilCalendar',
    cilChart = 'cilChart',
    cilChartPie = 'cilChartPie',
    cilCheck = 'cilCheck',
    cilChevronLeft = 'cilChevronLeft',
    cilChevronRight = 'cilChevronRight',
    cilCloudDownload = 'cilCloudDownload',
    cilCloudUpload = 'cilCloudUpload',
    cilCode = 'cilCode',
    cilCog = 'cilCog',
    cilCommentSquare = 'cilCommentSquare',
    cilCreditCard = 'cilCreditCard',
    cilCursor = 'cilCursor',
    cilDollar = 'cilDollar',
    cilDrop = 'cilDrop',
    cilEnvelopeClosed = 'cilEnvelopeClosed',
    cilEnvelopeOpen = 'cilEnvelopeOpen',
    cilEqualizer = 'cilEqualizer',
    cilFile = 'cilFile',
    cilFilter = 'cilFilter',
    cilFolderOpen = 'cilFolderOpen',
    cilGrid = 'cilGrid',
    cilHome = 'cilHome',
    cilInbox = 'cilInbox',
    cilIndentDecrease = 'cilIndentDecrease',
    cilIndentIncrease = 'cilIndentIncrease',
    cilInfo = 'cilInfo',
    cilInput = 'cilInput',
    cilItalic = 'cilItalic',
    cilJustifyCenter = 'cilJustifyCenter',
    cilJustifyLeft = 'cilJustifyLeft',
    cilLayers = 'cilLayers',
    cilLibrary = 'cilLibrary',
    cilList = 'cilList',
    cilListNumbered = 'cilListNumbered',
    cilListRich = 'cilListRich',
    cilLocationPin = 'cilLocationPin',
    cilLockLocked = 'cilLockLocked',
    cilMagnifyingGlass = 'cilMagnifyingGlass',
    cilMap = 'cilMap',
    cilMediaPlay = 'cilMediaPlay',
    cilMenu = 'cilMenu',
    cilMinus = 'cilMinus',
    cilMoon = 'cilMoon',
    cilNotes = 'cilNotes',
    cilOptions = 'cilOptions',
    cilPaperclip = 'cilPaperclip',
    cilPaperPlane = 'cilPaperPlane',
    cilPen = 'cilPen',
    cilPencil = 'cilPencil',
    cilPeople = 'cilPeople',
    cilPrint = 'cilPrint',
    cilPuzzle = 'cilPuzzle',
    cilReportSlash = 'cilReportSlash',
    cilSave = 'cilSave',
    cilSearch = 'cilSearch',
    cilSettings = 'cilSettings',
    cilShare = 'cilShare',
    cilShareAll = 'cilShareAll',
    cilShareBoxed = 'cilShareBoxed',
    cilSpeech = 'cilSpeech',
    cilSpeedometer = 'cilSpeedometer',
    cilSpreadsheet = 'cilSpreadsheet',
    cilStar = 'cilStar',
    cilStorage = 'cilStorage',
    cilSun = 'cilSun',
    cilSync = 'cilSync',
    cilTags = 'cilTags',
    cilTask = 'cilTask',
    cilTrash = 'cilTrash',
    cilUnderline = 'cilUnderline',
    cilUser = 'cilUser',
    cilUserFemale = 'cilUserFemale',
    cilUserFollow = 'cilUserFollow',
    cilUserUnfollow = 'cilUserUnfollow',
    cilX = 'cilX',
    cilDataTransferDown = 'cilDataTransferDown',
    cilBarChart = 'cilBarChart',
    cilChartLine = 'cilChartLine',
    cilChild = 'cilChild',
    cilHistory = 'cilHistory',
    cilRoom = 'cilRoom',
    cilBook = 'cilBook',
    cilMoney = 'cilMoney'
}
